language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.9'
install:
  - pip install pylint
  - pip install coverage
script:
  - python -m unittest
  - pylint board.py game.py minesweeper.py minesweeper_details.py minesweeper_displays.py tile.py
