dist: jammy
language: python
python:
  - '3.8'
  - '3.9'
  - '3.10'
  - '3.11'
install:
  - pip install pylint
  - pip install coverage
script:
  - python -m unittest
  - pylint board.py game.py minesweeper.py minesweeper_details.py minesweeper_displays.py tile.py
  - coverage run -m unittest
  - coverage json
  - bash <(curl -s https://codecov.io/bash)
  - coverage erase
